### ISSUE TITLE
We should add a unit testing framework

### ISSUE THREAD

**Issue by erikerlandson** [radanalyticsio/silex#4]

**Comment by willb** [comment]
Totally agreed.  I'd was also thinking that I'd like to see us build up or adapt some tools for testing libraries and apps that use Spark.

(cc @rnowling, who may find this topic relevant to his interests)

**Comment by rnowling** [comment]
I'd be happy to help and do grunt work. I've mostly been using junit-like tests in the same style as Spark's for BPS Spark. I'd be interested in exploring additional approaches.

**Comment by willb** [comment]
I was thinking more that you might want to add a component to generate test data at some point in the future.
