### ISSUE TITLE
quick start with spark-shell

### ISSUE THREAD

**Issue by jkremser** [radanalyticsio/silex#72]
I like the way how https://github.com/LucaCanali/sparkMeasure#getting-started-examples-of-sparkmeasure-usage provide a code snippet for very quick start, what about something similar for silex?

It'd be easier, if it's in the maven central, but it's also possible with 'non-default' maven repos:

https://gist.github.com/Jiri-Kremser/efd968a3c8128fd125382da76b0f5b65

**Comment by willb** [comment]
Good idea!  We have a special console task for developers but a standalone example would be even nicer.

**Comment by jkremser** [comment]
oh, I didn't know about the special console... how does it work? You have to clone the repo and then run `sbt console`?

I can create a PR and add the snippet w/ spark-shell to the readme if you want.
