### ISSUE TITLE
RF Clustering fails with Spark 2.3

### ISSUE THREAD

**Issue by erikerlandson** [radanalyticsio/silex#76]

**Comment by erikerlandson** [comment]
This smells like they might have gone to splitting at midpoint of adjacent values.

**Comment by erikerlandson** [comment]
test failure looks like this:
```
[info] ClusteringRandomForestModelSpec:
[info] - should provide clustering enhancements *** FAILED ***
[info]   Seq(Vector((foo <= 0.5)), Vector((foo > 0.5), (bar in [0.0])), Vector((foo <= 0.5)), Vector((foo > 0.5), (bar in [0.0])), Vector((bar in [0.0])), Vector((bar in [1.0]), (foo <= 0.5)), Vector((foo <= 0.5)), Vector((foo > 0.5), (bar in [0.0])), Vector((foo <= 0.5)), Vector((foo > 0.5), (bar in [0.0]))) did not match Seq(Vector((foo <= 0.0)), Vector((foo > 0.0), (bar in [0.0])), Vector((foo <= 0.0)), Vector((foo > 0.0), (bar in [0.0])), Vector((bar in [0.0])), Vector((bar in [1.0]), (foo <= 0.0)), Vector((foo <= 0.0)), Vector((foo > 0.0), (bar in [0.0])), Vector((foo <= 0.0)), Vector((foo > 0.0), (bar in [0.0]))) (ClusteringRandomForestModel.scala:105)
```

**Comment by erikerlandson** [comment]
Yep, they merged this in 2.3.0 
https://issues.apache.org/jira/browse/SPARK-16957

**Comment by erikerlandson** [comment]
So the interesting question is, do we want to try and have unit tests that are aware of pre/post spark 2.3 logic, or just have test assume new midpoints for >= 2.3?  I'd vote for just assuming >= 2.3 in the tests, since we'll be at 2.4 soon

**Comment by willb** [comment]
Nice find.  I think it's fine to require Spark >= 2.3 for Silex 0.3.0 and above, so let's proceed with that assumption.

**Comment by erikerlandson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RF clulstering failing on silex with spark 2.3](https://trello.com/c/R96c8alo/729-rf-clulstering-failing-on-silex-with-spark-23)
